# Site settings
title: One page machine learning
email: wehong@cse.ust.hk
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/one-page-machine-learning" # the subpath of your site, e.g. /blog
url: "https://laftworld.github.io" # the base hostname & protocol for your site
author: laftworld
#twitter_username: jekyllrb
github_username:  laftworld
facebook_username: woneui.hong
#google_play: 'GDGX'
#google_plus_com: '109485346959707049693'  # Community link
#google_plus_per: '+GDGManagua'  #Personal link
#facebook_app_id: 12345

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: default    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

more_vert:
  option1:
    name: Open tutorials (Korean)
    link: https://opentutorials.org/module/3653
  option2:
    name: Youtube (Korean)
    link: https://www.youtube.com/watch?v=krK8N5omujc&list=PLEkZgsocS9J02K1j-5GhYQiYVqxGh3hQ7

disqus: true
#disqus_shortname: 'gdgmanagua'

# Build settings
markdown: kramdown

plugins:
 - jekyll-feed
