# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: One page machine learning
email: wehong@cse.ust.hk
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/one-page-machine-learning" # the subpath of your site, e.g. /blog
url: "https://laftworld.github.io" # the base hostname & protocol for your site
author: laftworld

# Gems
gems: [jekyll-paginate]

# Build settings
markdown: kramdown
paginate: 5
paginate_path: 'page:num/'
comments: true
excerpt_separator: <!-- more -->
plugins:
 - jekyll-feed
